"""add machine management tables

Revision ID: 2e172ffd71bd
Revises: 2f1b3d696a2b
Create Date: 2025-10-14 02:40:35.498329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e172ffd71bd'
down_revision = '2f1b3d696a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('service_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('services_offered', sa.String(length=255), nullable=True),
    sa.Column('preferred_assets', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_idle_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['machine_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_idle_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_idle_event_asset_id'), ['asset_id'], unique=False)

    op.create_table('machine_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_life_hours', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['machine_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_part_asset_id'), ['asset_id'], unique=False)

    op.create_table('machine_part_replacement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('replaced_on', sa.Date(), nullable=False),
    sa.Column('replaced_by', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['machine_part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machine_part_replacement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_part_replacement_part_id'), ['part_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_part_replacement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_part_replacement_part_id'))

    op.drop_table('machine_part_replacement')
    with op.batch_alter_table('machine_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_part_asset_id'))

    op.drop_table('machine_part')
    with op.batch_alter_table('machine_idle_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_idle_event_asset_id'))

    op.drop_table('machine_idle_event')
    op.drop_table('service_supplier')
    op.drop_table('machine_asset')
    # ### end Alembic commands ###
